import React, { useState, useEffect } from 'react';
import { useAdlerianBrain } from '../hooks/useAdlerianBrain';
import StrivingTracker from './StrivingTracker';
import InsightLog from './InsightLog';
import ResourceBridge from './ResourceBridge';
import TutorialCard from './TutorialCard';
import { Mic, Activity, Globe, Languages, Zap } from 'lucide-react';

// UI Text Translation Dictionary
const UI_TEXT = {
  en: {
    title: 'Navi',
    mode_col: 'Collectivist',
    mode_ind: 'Individualistic',
    resource_title: 'Daily Wisdom',
    resource_quote: 'The courage to be imperfect is the courage to be free.',
    resource_link: 'Campus Counseling',
    click_hint: 'Click the orb to begin...',
    listening: 'Navi is listening to your tone and pitch...',
    debug: 'GEMINI API CONNECTED • ADLERIAN CORE ONLINE'
  },
  zh: {
    title: 'Navi',
    mode_col: '集体主义模式',
    mode_ind: '个人主义模式',
    resource_title: '每日智慧',
    resource_quote: '拥有被讨厌的勇气，就是拥有自由的勇气。',
    resource_link: '校园心理咨询',
    click_hint: '点击光球开始对话...',
    listening: 'Navi 正在聆听你的声音和语调...',
    debug: 'Gemini 核心已连接 • 阿德勒引擎运行中'
  }
};

export default function NaviWebInterface() {
  const [culturalMode, setCulturalMode] = useState('collectivist');
  const [language, setLanguage] = useState('en'); // Language state: 'en' or 'zh'
  const [showTutorial, setShowTutorial] = useState(true); // Show tutorial by default
  const { processInput, brainState, setBrainState } = useAdlerianBrain();

  // Manage "Micro-Striving" tasks state
  const [tasks, setTasks] = useState([
    // Demo data - in real development, these would be generated by Gemini and auto-added
    { id: 1, text: language === 'zh' ? "深呼吸三次" : "Take 3 deep breaths", completed: false },
    { id: 2, text: language === 'zh' ? "写下自己的一个优点" : "Write down one strength", completed: true },
  ]);

  // Update tasks when language changes
  useEffect(() => {
    setTasks(prev => prev.map(task => {
      if (task.id === 1) {
        return { ...task, text: language === 'zh' ? "深呼吸三次" : "Take 3 deep breaths" };
      }
      if (task.id === 2) {
        return { ...task, text: language === 'zh' ? "写下自己的一个优点" : "Write down one strength" };
      }
      return task;
    }));
  }, [language]);

  // Manage insights/reframing log
  const [insights, setInsights] = useState([
    // Demo data
    {
      original: language === 'zh' ? "我失败了" : "I'm a failure",
      reframed: language === 'zh' ? "我还在学习，这条路暂时走不通" : "I'm learning what doesn't work yet",
      timestamp: new Date().toISOString()
    }
  ]);

  // Update insights when language changes
  useEffect(() => {
    setInsights([
      {
        original: language === 'zh' ? "我失败了" : "I'm a failure",
        reframed: language === 'zh' ? "我还在学习，这条路暂时走不通" : "I'm learning what doesn't work yet",
        timestamp: new Date().toISOString()
      }
    ]);
  }, [language]);

  const toggleTask = (id) => {
    setTasks(prev => prev.map(t => t.id === id ? { ...t, completed: !t.completed } : t));
  };

  // Extract action suggestions from Gemini response and add to tasks
  useEffect(() => {
    if (brainState.response && brainState.status === 'speaking') {
      // Simple pattern matching for action suggestions
      // In production, you could ask Gemini to format responses with [ACTION]: tags
      const actionPatterns = language === 'zh' 
        ? [
            /深呼吸/i,
            /喝.*水/i,
            /写下/i,
            /暂停.*下/i,
            /设定.*小目标/i,
          ]
        : [
            /take\s+\d+\s+deep\s+breaths?/i,
            /drink\s+(a\s+)?glass\s+of\s+water/i,
            /write\s+down/i,
            /pause\s+(for\s+)?a\s+moment/i,
            /set\s+a\s+small\s+goal/i,
          ];

      actionPatterns.forEach(pattern => {
        const match = brainState.response.match(pattern);
        if (match && !tasks.some(t => t.text.toLowerCase().includes(match[0].toLowerCase()))) {
          const newTask = {
            id: Date.now(),
            text: match[0].charAt(0).toUpperCase() + match[0].slice(1),
            completed: false
          };
          setTasks(prev => [...prev, newTask]);
        }
      });
    }
  }, [brainState.response, brainState.status, language, tasks]);

  // Simulate recording and multimodal analysis
  const handleInteraction = () => {
    if (brainState.status !== 'idle') return;

    // Close tutorial when user clicks the orb
    setShowTutorial(false);

    // 1. Change status to listening
    setBrainState(prev => ({ ...prev, status: 'listening' }));

    // 2. Simulate recording process (3 seconds)
    setTimeout(() => {
      // Simulate extracted data from microphone
      const simulatedInput = language === 'zh' 
        ? "我觉得压力好大，考试可能要挂了。"
        : "I feel so overwhelmed by my finals. I'm scared I'll fail everyone.";
      
      // Simulate audio feature analysis (Pitch/Speed)
      const simulatedMetrics = {
        culturalMode: culturalMode,
        language: language, // Pass language to brain
        pitch: "High/Shaky", // Simulate anxious pitch
        speed: "Fast"       // Simulate rapid speech
      };

      // 3. Send to Gemini Brain
      processInput(simulatedInput, simulatedMetrics);
    }, 3000);
  };

  // Get detected emotion from brain state for ResourceBridge
  const detectedEmotion = brainState.status === 'speaking' && brainState.response 
    ? (brainState.response.toLowerCase().includes('anxiety') || brainState.response.toLowerCase().includes('anxious') || brainState.response.includes('焦虑') ? 'anxiety' : 'neutral')
    : 'neutral';

  // Get current language text
  const t = UI_TEXT[language];

  return (
    <div className="min-h-screen bg-[#FDFCF8] text-stone-600 font-sans relative overflow-hidden transition-colors duration-1000 p-4 md:p-8">
      
      {/* Background Glow: Warm sunrise colors */}
      <div className={`absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-orange-100 rounded-full blur-[120px] opacity-60 pointer-events-none mix-blend-multiply transition-all duration-700
        ${brainState.status === 'listening' ? 'scale-110 opacity-70' : ''}
        ${brainState.status === 'thinking' ? 'scale-90 opacity-50 bg-purple-100' : ''}
        ${brainState.status === 'speaking' ? 'scale-105 opacity-60 bg-teal-100' : ''}
      `}></div>
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-purple-100 rounded-full blur-[100px] opacity-40 pointer-events-none mix-blend-multiply"></div>

      {/* Top Header */}
      <header className="flex justify-between items-center mb-6 md:mb-8 relative z-20">
        <div className="flex items-center gap-2 font-bold text-xl md:text-2xl tracking-tight text-stone-700">
          {t.title}<span className="text-orange-400">.web</span>
        </div>
        <div className="flex gap-3">
          {/* Language Toggle Button */}
          <button 
            onClick={() => setLanguage(prev => prev === 'en' ? 'zh' : 'en')}
            className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-white border border-stone-200 text-xs font-medium hover:bg-orange-50 transition text-stone-600 shadow-sm"
          >
            <Languages size={14} /> {language === 'en' ? 'EN' : '中文'}
          </button>
          {/* Cultural Mode Toggle */}
          <button 
            onClick={() => setCulturalMode(prev => prev === 'collectivist' ? 'individualistic' : 'collectivist')}
            className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-white border border-stone-200 text-xs font-medium hover:bg-orange-50 transition text-stone-600 shadow-sm"
          >
            <Globe size={12} /> {culturalMode === 'collectivist' ? t.mode_col : t.mode_ind}
          </button>
        </div>
      </header>

      {/* Core Grid Layout */}
      <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-4 md:gap-6 h-[calc(100vh-180px)] min-h-[600px]">
        
        {/* Left Sidebar: Resource Bridge & Insights (3 columns) */}
        <div className="hidden lg:flex lg:col-span-3 flex-col gap-4 h-full">
          <div className="flex-1">
            <ResourceBridge detectedEmotion={detectedEmotion} language={language} />
          </div>
          <div className="flex-1">
            <InsightLog insights={insights} language={language} />
          </div>
        </div>

        {/* Center Core: Navi Orb (6 columns) */}
        <div className="col-span-1 lg:col-span-6 flex flex-col items-center justify-center relative mt-10 lg:mt-0">
          {/* Tutorial Card - Show only when idle and tutorial is enabled */}
          {showTutorial && brainState.status === 'idle' && (
            <TutorialCard 
              language={language} 
              onClose={() => setShowTutorial(false)} 
            />
          )}
          
          {/* The Orb - Organic, warm design */}
          <div 
            onClick={handleInteraction}
            className={`w-40 h-40 md:w-48 md:h-48 rounded-full flex items-center justify-center cursor-pointer transition-all duration-700 relative mb-6 md:mb-8 backdrop-blur-sm
              ${brainState.status === 'idle' ? 'bg-white shadow-[0_10px_30px_rgba(0,0,0,0.05)] border border-stone-100 hover:shadow-lg' : ''}
              ${brainState.status === 'listening' ? 'bg-orange-200/50 shadow-[0_0_60px_rgba(251,146,60,0.4)] scale-110' : ''}
              ${brainState.status === 'thinking' ? 'bg-purple-100/50 shadow-[0_0_60px_rgba(192,132,252,0.3)] animate-spin-slow' : ''}
              ${brainState.status === 'speaking' ? 'bg-teal-100/50 shadow-[0_0_60px_rgba(45,212,191,0.3)]' : ''}
            `}
          >
            {brainState.status === 'idle' && <Mic size={32} className="text-stone-400" />}
            {brainState.status === 'listening' && (
              <div className="flex gap-1 h-10 items-center">
                {[1,2,3,4,5].map(i => (
                  <div key={i} className="w-1.5 bg-orange-400 animate-bounce rounded-full" style={{height: '60%', animationDelay: `${i * 0.1}s`}}></div>
                ))}
              </div>
            )}
            {brainState.status === 'thinking' && <Zap size={40} className="text-purple-500 animate-pulse" />}
            {brainState.status === 'speaking' && <Activity size={40} className="text-teal-600 animate-pulse" />}
          </div>

          {/* Conversation Output */}
          <div className="h-32 w-full text-center flex items-center justify-center px-4">
            {brainState.status === 'listening' && (
              <p className="text-stone-500 animate-pulse text-sm md:text-base">{t.listening}</p>
            )}
            
            {brainState.status === 'speaking' && brainState.response && (
              <div className="animate-fade-in-up space-y-4 w-full">
                <p className="text-lg md:text-xl lg:text-2xl font-light leading-relaxed text-stone-700">
                  "{brainState.response}"
                </p>
                <div className="text-xs text-stone-400 uppercase tracking-widest">
                  Intent: {brainState.intent}
                </div>
              </div>
            )}

            {brainState.status === 'idle' && !brainState.response && (
              <p className="text-stone-400 text-sm md:text-base">{t.click_hint}</p>
            )}
          </div>
        </div>

        {/* Right Sidebar: Striving Tracker (3 columns) */}
        <div className="hidden lg:flex lg:col-span-3 h-full">
          <StrivingTracker tasks={tasks} onToggle={toggleTask} language={language} />
        </div>
      </div>

      {/* Mobile View: Show modules below on small screens */}
      <div className="lg:hidden mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="h-64">
          <StrivingTracker tasks={tasks} onToggle={toggleTask} language={language} />
        </div>
        <div className="h-64">
          <ResourceBridge detectedEmotion={detectedEmotion} language={language} />
        </div>
        <div className="md:col-span-2 h-64">
          <InsightLog insights={insights} language={language} />
        </div>
      </div>

      {/* Bottom Debug Bar */}
      <div className="absolute bottom-4 left-0 w-full text-center text-xs text-stone-400 font-mono z-10">
        {t.debug}
      </div>
    </div>
  );
}
